# backend/config.py
# 한화 방산 미래전략실 - 설정 및 무기체계/분쟁 매핑 사전 (FastAPI)

DAILY_DEFENSE_RSS_URL = 'https://www.dailydefense.co.kr/rss/allArticle.xml'
DAILY_DEFENSE_TOP_RSS_URL = 'https://www.dailydefense.co.kr/rss/clickTop.xml'

# Armed Conflicts 29개 활성 분쟁지 정의
CONFLICT_SLUGS = [
    'russia-ukraine-war',
    'israel-gaza-war',
    'iran-israel-war',
    'lebanon-israel-conflict',
    'yemen-war',
    'syria-civil-war',
    'iraq-conflict',
    'turkey-kurdish-conflict',
    'sudan-civil-war',
    'south-sudan-conflict',
    'somalia-al-shabaab',
    'ethiopia-conflict',
    'dr-congo-m23-conflict',
    'central-african-republic',
    'nigeria-boko-haram',
    'sahel-insurgency',
    'mozambique-cabo-delgado',
    'libya-conflict',
    'afghanistan-conflict',
    'pakistan-conflict',
    'india-pakistan-kashmir',
    'myanmar-civil-war',
    'taiwan-strait-tensions',
    'south-china-sea-disputes',
    'armenia-azerbaijan-conflict',
    'mexico-drug-war',
    'colombia-conflict',
    'haiti-gang-violence',
    'ecuador-conflict'
]

# 분쟁 한국어 메타데이터 매핑
CONFLICT_META_KO = {
    'russia-ukraine-war': {'nameKo': '러시아-우크라이나 전쟁', 'regionKo': '동유럽', 'mainTheaters': '도네츠크, 자포리자, 쿠르스크, 하르키우'},
    'israel-gaza-war': {'nameKo': '이스라엘-하마스(가자) 전쟁', 'regionKo': '중동', 'mainTheaters': '가자지구, 라파, 서안지구'},
    'iran-israel-war': {'nameKo': '이란-이스라엘 분쟁', 'regionKo': '중동', 'mainTheaters': '테헤란, 텔아비브, 시리아 국경'},
    'lebanon-israel-conflict': {'nameKo': '레바논-이스라엘(헤즈볼라) 충돌', 'regionKo': '중동', 'mainTheaters': '남부 레바논, 베이루트'},
    'yemen-war': {'nameKo': '예멘 내전 & 홍해 후티 위기', 'regionKo': '중동/홍해', 'mainTheaters': '홍해 항로, 사나, 아덴만'},
    'syria-civil-war': {'nameKo': '시리아 내전', 'regionKo': '중동', 'mainTheaters': '알레포, 이들립, 다마스쿠스'},
    'iraq-conflict': {'nameKo': '이라크 안보 위기', 'regionKo': '중동', 'mainTheaters': '바그다드, 에르빌'},
    'turkey-kurdish-conflict': {'nameKo': '튀르키예-쿠르드(PKK) 분쟁', 'regionKo': '중동/아나톨리아', 'mainTheaters': '이라크 북부 국경, 시리아 북부'},
    'sudan-civil-war': {'nameKo': '수단 내전 (정규군 vs RSF)', 'regionKo': '아프리카', 'mainTheaters': '하르툼, 다르푸르'},
    'south-sudan-conflict': {'nameKo': '남수단 분쟁', 'regionKo': '아프리카', 'mainTheaters': '주바, 유니티주'},
    'somalia-al-shabaab': {'nameKo': '소말리아-알샤바브 분쟁', 'regionKo': '동아프리카', 'mainTheaters': '모가디슈, 소말릴란드 국경'},
    'ethiopia-conflict': {'nameKo': '에티오피아 암하라/오로모 분쟁', 'regionKo': '동아프리카', 'mainTheaters': '암하라주, 티그라이'},
    'dr-congo-m23-conflict': {'nameKo': '민주콩고(DRC)-M23 반군 분쟁', 'regionKo': '중앙아프리카', 'mainTheaters': '북키부주, 고마'},
    'central-african-republic': {'nameKo': '중앙아프리카공화국 분쟁', 'regionKo': '중앙아프리카', 'mainTheaters': '방기, 국경지대'},
    'nigeria-boko-haram': {'nameKo': '나이지리아 보코하람/ISWAP 반란', 'regionKo': '서아프리카', 'mainTheaters': '보르노주, 차드호'},
    'sahel-insurgency': {'nameKo': '사헬 지대 이슬람 반군 (말리/니제르/부르키나파소)', 'regionKo': '서아프리카', 'mainTheaters': '3국 접경지대'},
    'mozambique-cabo-delgado': {'nameKo': '모잠비크 카보델가도 반군', 'regionKo': '남아프리카', 'mainTheaters': '카보델가도주 가스전 지대'},
    'libya-conflict': {'nameKo': '리비아 동서 정권 대립', 'regionKo': '북아프리카', 'mainTheaters': '트리폴리, 벵가지, 시르테'},
    'afghanistan-conflict': {'nameKo': '아프가니스탄 탈레반-ISKP 분쟁', 'regionKo': '서남아시아', 'mainTheaters': '카불, 낭가르하르'},
    'pakistan-conflict': {'nameKo': '파키스탄 TTP & 발루치 분쟁', 'regionKo': '서남아시아', 'mainTheaters': '카이베르파크툰크와, 발루치스탄'},
    'india-pakistan-kashmir': {'nameKo': '인도-파키스탄 카슈미르 분쟁', 'regionKo': '남아시아', 'mainTheaters': '통제선(LoC), 라다크 국경'},
    'myanmar-civil-war': {'nameKo': '미얀마 내전 (군부 vs NUG/반군)', 'regionKo': '동남아시아', 'mainTheaters': '만달레이, 샨주, 라카인주'},
    'taiwan-strait-tensions': {'nameKo': '대만 해협 긴장 & 양안 위기', 'regionKo': '동아시아', 'mainTheaters': '대만 해협 중간선, 펑후제도, 방공식별구역'},
    'south-china-sea-disputes': {'nameKo': '남중국해 영유권 분쟁 (필리핀/베트남 vs 중국)', 'regionKo': '동남아시아/해양', 'mainTheaters': '스카버러 암초, 세컨드 토마스 암초, 스프래틀리 군도'},
    'armenia-azerbaijan-conflict': {'nameKo': '아르메니아-아제르바이잔 국경 분쟁', 'regionKo': '코카서스', 'mainTheaters': '잔게주르 회랑, 국경 접경지'},
    'mexico-drug-war': {'nameKo': '멕시코 마약 카르텔 전쟁', 'regionKo': '중남미', 'mainTheaters': '시날로아, 할리스코, 국경도시'},
    'colombia-conflict': {'nameKo': '콜롬비아 ELN 및 FARC 반군', 'regionKo': '남미', 'mainTheaters': '안데스 정글, 베네수엘라 국경'},
    'haiti-gang-violence': {'nameKo': '아이티 갱단 폭력 위기', 'regionKo': '카리브해', 'mainTheaters': '포르토프랭스'},
    'ecuador-conflict': {'nameKo': '에콰도르 치안 비상사태', 'regionKo': '남미', 'mainTheaters': '과야킬, 태평양 연안 마약루트'}
}

# 전 세계 29개 분쟁지 전장 지형 및 기후(온도/습도/환경위협) 프로파일 & 실제 국가 지형 실사 사진
CONFLICT_TERRAIN_CLIMATE = {   'afghanistan-conflict': {   'country': '아프가니스탄 (Afghanistan)',
                                'countryEn': 'Afghanistan',
                                'humidity': {'avg': 25, 'desc': '건조 (평균 25%)', 'max': 50},
                                'specialHazards': ['해발 3,500m 고고도 산소 희박 헬기/엔진 출력 급감', '동절기 영하 20도 혹한', '협곡 매복로 대전차 지뢰'],
                                'tempRange': {'desc': '산간 혹한 (-20°C) ~ 하계 건조 (43°C)', 'max': 43, 'min': -20},
                                'terrainDescription': '해발 3,000~5,000m의 눈 덮인 거대한 바위산맥과 황량한 협곡. 도로가 극소수이며 지형적 고립이 심함.',
                                'terrainPhoto': {   'caption': '아프가니스탄 힌두쿠시 고산 바위산 및 협곡 실사',
                                                    'location': '판지시르 협곡 및 힌두쿠시 산맥',
                                                    'tags': ['고산 바위산', '희박 산소', '영하 20도 혹한'],
                                                    'url': 'https://upload.wikimedia.org/wikipedia/commons/1/10/Hindu_Kush_satellite_image.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                'terrainType': '힌두쿠시 험준 산악 & 고원 협곡'},
    'armenia-azerbaijan-conflict': {   'country': '아르메니아-아제르바이잔 (Caucasus)',
                                       'countryEn': 'Armenia / Azerbaijan',
                                       'humidity': {'avg': 45, 'desc': '평균 45%', 'max': 70},
                                       'specialHazards': [   '수목 차폐 전무한 능선 드론 표적화',
                                                             '동절기 결빙과 짙은 고산 안개',
                                                             '험준한 능선 전차 기동로 제한'],
                                       'tempRange': {'desc': '고원 혹한 (-18°C) ~ 하계 온난 (35°C)', 'max': 35, 'min': -18},
                                       'terrainDescription': '해발 2,000m 이상의 굴곡진 바위 능선과 초원. 수목이 거의 없어 무인기 및 정밀유도무기에 완전 '
                                                             '노출되는 개활 능선전.',
                                       'terrainPhoto': {   'caption': '코카서스 잔게주르(슈니크) 고원 바위 능선 및 초원 실사',
                                                           'location': '잔게주르 회랑 국경 능선',
                                                           'tags': ['코카서스 능선', '드론 관측 노출', '고원 혹한'],
                                                           'url': 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Landscape_in_Syunik%2C_river%2C_mountains.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                       'terrainType': '코카서스 고원 초원 & 바위 능선'},
    'central-african-republic': {   'country': '중앙아프리카공화국 (CAR)',
                                    'countryEn': 'CAR',
                                    'humidity': {'avg': 60, 'desc': '우기 92% 다습', 'max': 92},
                                    'specialHazards': ['라테라이트 적색토 점착으로 궤도 고착', '우기 하천 범람 교량 유실', '고온다습 환경 부식'],
                                    'tempRange': {'desc': '열대 사바나 (18°C ~ 39°C)', 'max': 39, 'min': 18},
                                    'terrainDescription': '붉은 라테라이트 점토 비포장 도로와 우림 수림대. 우기 시 도로가 붉은 진흙탕으로 변해 차량 바퀴가 헛돌고 '
                                                          '교량이 유실됨.',
                                    'terrainPhoto': {   'caption': '중앙아프리카 적색토 사바나 평원 및 비포장 수림로 실사',
                                                        'location': '중부 방기 외곽 사바나',
                                                        'tags': ['라테라이트 적색토', '사바나 수림', '우기 진흙탕'],
                                                        'url': 'https://upload.wikimedia.org/wikipedia/commons/4/41/The_Greater_Virunga_Landscape%2C_Africa_%28Copernicus_2026-03-03%29.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                    'terrainType': '열대 사바나 수림 & 라테라이트 적색토'},
    'colombia-conflict': {   'country': '콜롬비아 (Colombia)',
                             'countryEn': 'Colombia',
                             'humidity': {'avg': 85, 'desc': '연중 85~98% 극고습', 'max': 98},
                             'specialHazards': ['상시 운무로 가시거리 50m 이하 급감', '상대습도 98% 광학 센서 결로/부식', '진흙 수렁 및 급경사 전복 위험'],
                             'tempRange': {'desc': '안데스 운무림 (14°C ~ 35°C)', 'max': 35, 'min': 14},
                             'terrainDescription': '해발 2,000m의 짙은 안개와 비에 젖은 안데스 산악림과 아마존 저지대 정글. 1년 내내 비가 내리고 습도가 95% '
                                                   '이상을 상회.',
                             'terrainPhoto': {   'caption': '콜롬비아 안데스 운무림 및 아마존 접경 정글 실사',
                                                 'location': '카케타·푸투마요 정글 안데스 동사면',
                                                 'tags': ['안데스 운무림', '98% 극고습', '상시 안개 결로'],
                                                 'url': 'https://upload.wikimedia.org/wikipedia/commons/3/32/Amanecer_en_la_Cordillera_central_-_Flickr_-_Alejandro_Bayer.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                             'terrainType': '안데스 운무림(Cloud Forest) & 아마존 정글'},
    'dr-congo-m23-conflict': {   'country': '민주콩고 (DR Congo)',
                                 'countryEn': 'DR Congo',
                                 'humidity': {'avg': 85, 'desc': '연중 85~98% 극고습', 'max': 98},
                                 'specialHazards': ['상대습도 98% 극단적 다습 배선 부식', '울창한 캐노피 GPS/위성 신호 차폐', '화산암 울퉁불퉁 험지'],
                                 'tempRange': {'desc': '열대 우림 (16°C ~ 32°C)', 'max': 32, 'min': 16},
                                 'terrainDescription': '비룽가 국립공원의 험준한 화산암 암반과 울창한 적도 정글. 연중 쏟아지는 폭우와 높은 습도로 지표면이 상시 수렁 '
                                                       '상태.',
                                 'terrainPhoto': {   'caption': '민주콩고 북키부 비룽가 화산 지대 및 열대우림 실사',
                                                     'location': '북키부주 고마 외곽 화산림',
                                                     'tags': ['적도 열대우림', '98% 극고습', '화산암 험지'],
                                                     'url': 'https://upload.wikimedia.org/wikipedia/commons/0/03/Gazelle_in_Virunga_National_Park.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                 'terrainType': '북키부 화산 지대 & 적도 원시 열대우림'},
    'ecuador-conflict': {   'country': '에콰도르 (Ecuador)',
                            'countryEn': 'Ecuador',
                            'humidity': {'avg': 75, 'desc': '평균 75% / 하계 92%', 'max': 92},
                            'specialHazards': ['맹그로브 수로 조수간만 차 좌초', '고습도 해무 전자장비 부식', '항만 콘크리트 협소 기동로'],
                            'tempRange': {'desc': '태평양 연안 (19°C ~ 34°C)', 'max': 34, 'min': 19},
                            'terrainDescription': '과야킬 하구의 복잡한 맹그로브 수로와 항만, 안데스 산맥 기슭. 해상 마약루트와 고온다습한 열대 연안 기후.',
                            'terrainPhoto': {   'caption': '에콰도르 과야스강 하구 및 태평양 연안 맹그로브 실사',
                                                'location': '과야스강 하구 태평양 연안',
                                                'tags': ['맹그로브 하구', '해무 부식', '항만 수로'],
                                                'url': 'https://upload.wikimedia.org/wikipedia/commons/8/81/Guayas_from_Santa_Ana.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                            'terrainType': '태평양 연안 항만, 맹그로브 하구 & 안데스 기슭'},
    'ethiopia-conflict': {   'country': '에티오피아 (Ethiopia)',
                             'countryEn': 'Ethiopia',
                             'humidity': {'avg': 50, 'desc': '평균 50%', 'max': 80},
                             'specialHazards': ['해발 2,500m 고고도 산소 희박 출력 저하', '수직 단애 절벽 우회로 부재', '우기 돌발성 계곡 급류'],
                             'tempRange': {'desc': '고원 냉량 (8°C) ~ 온난 (30°C)', 'max': 30, 'min': 8},
                             'terrainDescription': '해발 2,000~3,000m의 광대한 고원과 수직 절벽 협곡. 희박한 공기와 거친 화산암 지형으로 기갑 전력 전개가 '
                                                   '극히 제한됨.',
                             'terrainPhoto': {   'caption': '에티오피아 시미엔 고원 단애 및 침식 협곡 실사',
                                                 'location': '암하라주·티그라이 고원 절벽',
                                                 'tags': ['고원 절벽', '희박 공기', '침식 협곡'],
                                                 'url': 'https://upload.wikimedia.org/wikipedia/commons/8/84/Simien_Mountains_Landscape%2C_Ethiopia_%282462794039%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                             'terrainType': '해발 2,500m 고원 단애 & 침식 협곡'},
    'haiti-gang-violence': {   'country': '아이티 (Haiti)',
                               'countryEn': 'Haiti',
                               'humidity': {'avg': 70, 'desc': '평균 70%', 'max': 88},
                               'specialHazards': ['비좁은 골목 장갑차 선회 반경 제한', '폭우 시 배수 불량 도심 침수', '옥상 화염병/소화기 기습'],
                               'tempRange': {'desc': '열대 해안 (20°C ~ 36°C)', 'max': 36, 'min': 20},
                               'terrainDescription': '포르토프랭스의 비좁은 콘크리트 미로 골목과 해안 저지대. 장갑차 진입이 불가능한 좁은 통로와 열대성 폭우 침수 '
                                                     '지형.',
                               'terrainPhoto': {   'caption': '아이티 포르토프랭스 도심 비탈 및 연안 슬럼 실사',
                                                   'location': '포르토프랭스 도심 슬럼',
                                                   'tags': ['도시 미로 슬럼', '폭우 침수', '초근접전'],
                                                   'url': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Downtown_Port_au_Prince_after_earthquake.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                               'terrainType': '카리브해 연안 도시 슬럼 & 산비탈 밀집지'},
    'india-pakistan-kashmir': {   'country': '인도-파키스탄 카슈미르 (Kashmir)',
                                  'countryEn': 'India / Pakistan',
                                  'humidity': {'avg': 40, 'desc': '설원 결빙', 'max': 70},
                                  'specialHazards': ['영하 45도 엔진 오일/연료 동결', '해발 5,500m 산소 부족 시동 불능', '눈사태 및 크레바스 붕괴'],
                                  'tempRange': {'desc': '빙하 극저온 (-45°C) ~ 하계 온난 (22°C)', 'max': 22, 'min': -45},
                                  'terrainDescription': '해발 5,000~6,500m의 세계 최고도 전장. 만년설과 크레바스, 평지의 50%에 불과한 산소 분압, 영하 '
                                                        '45도의 극한 혹한.',
                                  'terrainPhoto': {   'caption': '카슈미르 카라코람 설산 및 시아첸 만년설 빙하 실사',
                                                      'location': '통제선(LoC) 시아첸 빙하',
                                                      'tags': ['세계 최고도 전장', '영하 45도', '시아첸 빙하'],
                                                      'url': 'https://upload.wikimedia.org/wikipedia/commons/5/56/Fanny_Bullock_Workman_while_crossing_a_glacier_river_near_Siachen_glacier_1912.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                  'terrainType': '히말라야 카라코람 만년설 & 시아첸 빙하'},
    'iran-israel-war': {   'country': '이란 고원 (Iran)',
                           'countryEn': 'Iran',
                           'humidity': {'avg': 25, 'desc': '극건조 (평균 25%)', 'max': 45},
                           'specialHazards': ['하절기 45°C 초과 극고온 엔진 과열', '초미세 실리카 모래 분진 침투', '고고도 희박 산소 출력 저하'],
                           'tempRange': {'desc': '고원 동절기 (-5°C) ~ 사막 혹서기 (45°C)', 'max': 45, 'min': -5},
                           'terrainDescription': '해발 1,000~2,500m의 건조 고원과 거친 바위 산악. 지표면이 메마른 암반과 자갈 사막으로 이루어져 있으며 주야간 '
                                                 '일교차가 극심함.',
                           'terrainPhoto': {   'caption': '이란 자그로스 험준 산악 암반 및 건조 고원 실사',
                                               'location': '이란 중서부 자그로스 산맥',
                                               'tags': ['고원 사막', '암반 산악', '극건조 고온'],
                                               'url': 'https://upload.wikimedia.org/wikipedia/commons/5/54/Landscape_of_Shadegan.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                           'terrainType': '내륙 건조 고원 & 자그로스 험준 산악'},
    'iraq-conflict': {   'country': '이라크 (Iraq)',
                         'countryEn': 'Iraq',
                         'humidity': {'avg': 20, 'desc': '극건조 (평균 20%)', 'max': 45},
                         'specialHazards': ['50°C 초과 살인적 폭염 전자장비 오작동', '샤말(Shamal) 강풍 모래폭풍', '미세 충적토 모래 침투'],
                         'tempRange': {'desc': '동절기 (4°C) ~ 혹서기 (51°C 살인적 폭염)', 'max': 51, 'min': 4},
                         'terrainDescription': '티그리스/유프라테스강 주변 평탄한 토사 지대와 서부 광활한 자갈 사막. 하계 기온 50도를 웃도는 세계 최극단 혹서 전장.',
                         'terrainPhoto': {   'caption': '이라크 메소포타미아 평원 및 티그리스-유프라테스 유역 실사',
                                             'location': '중부 안바르 사막 & 유역 평야',
                                             'tags': ['충적 평야', '50도 폭염', '샤말 모래폭풍'],
                                             'url': 'https://upload.wikimedia.org/wikipedia/commons/7/73/%D9%87%D9%88%D8%B1_%D8%A7%D9%84%D8%AC%D8%A8%D8%A7%D9%8A%D8%B4.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                         'terrainType': '메소포타미아 충적 평야 & 서부 사막'},
    'israel-gaza-war': {   'country': '가자지구 & 이스라엘 (Gaza / Israel)',
                           'countryEn': 'Gaza Strip / Israel',
                           'humidity': {'avg': 65, 'desc': '연안 평균 65% / 야간 82%', 'max': 82},
                           'specialHazards': ['시가지 콘크리트 잔해 궤도/타이어 파손', '해안 염무 및 미세 모래 분진 흡입', '초근접 대전차 로켓 매복'],
                           'tempRange': {'desc': '온화한 동절기 (8°C) ~ 고온 건조 하계 (38°C)', 'max': 38, 'min': 8},
                           'terrainDescription': '해안 사구 지대와 빽빽한 콘크리트 건축물 군락. 파괴된 콘크리트 잔해로 기동로가 극도로 협소하며 지하 터널망과 연결된 복합 '
                                                 '시가지 지형.',
                           'terrainPhoto': {   'caption': '가자지구 지중해 연안 모래 및 연안 전장 실사',
                                               'location': '가자 남부 해안 회랑',
                                               'tags': ['연안 모래', '고밀도 시가전', '폐허 잔해'],
                                               'url': 'https://upload.wikimedia.org/wikipedia/commons/6/6d/The_fish_harbour_colors_at_the_end_of_the_day_%2850080131752%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                           'terrainType': '지중해 연안 건조 모래 & 고밀도 시가지 잔해'},
    'lebanon-israel-conflict': {   'country': '레바논 (Lebanon)',
                                   'countryEn': 'Lebanon',
                                   'humidity': {'avg': 55, 'desc': '평균 55%', 'max': 75},
                                   'specialHazards': ['석회암 급경사 전차 기동로 협소', '지하 벙커/터널 매복 화망', '하계 건조 수목 화재'],
                                   'tempRange': {'desc': '산간 저온 (4°C) ~ 하계 온난 (36°C)', 'max': 36, 'min': 4},
                                   'terrainDescription': '석회암 바위 언덕, 올리브 수림, 깊은 침식 계곡. 고지대 매복 진지 요새화에 유리하나 중장비의 등판각 및 '
                                                         '기동로가 극히 제한적임.',
                                   'terrainPhoto': {   'caption': '남부 레바논 리타니강 협곡 및 암석 구릉 실사',
                                                       'location': '남부 레바논 국경 구릉지대',
                                                       'tags': ['석회암 구릉', '협곡', '자연 요새'],
                                                       'url': 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Australian_forces_cross_the_Litani_River%2C_1941.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                   'terrainType': '지중해성 암석 구릉 & 리타니강 협곡'},
    'libya-conflict': {   'country': '리비아 (Libya)',
                          'countryEn': 'Libya',
                          'humidity': {'avg': 30, 'desc': '사막 건조 (30%)', 'max': 65},
                          'specialHazards': ['기블리(Ghibli) 모래폭풍 시정 10m 미만', '장거리 기동 타이어 마모', '엄폐물 없는 개활지'],
                          'tempRange': {'desc': '동절기 (6°C) ~ 하계 사막 (46°C)', 'max': 46, 'min': 6},
                          'terrainDescription': '지중해 연안 고속도로 주변 평탄지와 내륙의 광활한 자갈 사막. 장거리 고속 종심 기동과 공중 지원이 승패를 좌우함.',
                          'terrainPhoto': {   'caption': '리비아 사하라 자갈 사막(Serir) 평원 실사',
                                              'location': '시르테만 연안 및 내륙 유전 지대',
                                              'tags': ['자갈 사막', '고속 종심 기동', '기블리 모래폭풍'],
                                              'url': 'https://upload.wikimedia.org/wikipedia/commons/0/06/Libya_4432_Ghadames_Luca_Galuzzi_2007.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                          'terrainType': '지중해 연안 평원 & 사하라 세리르(Serir) 자갈 사막'},
    'mexico-drug-war': {   'country': '멕시코 (Mexico)',
                           'countryEn': 'Mexico',
                           'humidity': {'avg': 35, 'desc': '건조 35%', 'max': 70},
                           'specialHazards': ['사막 극건조 분진 흡입 마모', '고밀도 시가지 기습 대구경 저격', '산악 험로 단절'],
                           'tempRange': {'desc': '야간 (6°C) ~ 사막 폭염 (43°C)', 'max': 43, 'min': 6},
                           'terrainDescription': '메마른 선인장 사막과 바위 산악, 마약 카르텔이 장악한 국경 도시. 사막 분진과 시가지 시야 차단이 혼재함.',
                           'terrainPhoto': {   'caption': '멕시코 북부 소노라 사막 및 바위 산악 실사',
                                               'location': '시날로아 및 북부 국경 사막',
                                               'tags': ['소노라 사막', '바위 산악', '카르텔 도시'],
                                               'url': 'https://upload.wikimedia.org/wikipedia/commons/a/ae/San_Carlos_Sonora_landscape.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                           'terrainType': '시에라 마드레 산악 & 북부 소노라 사막'},
    'mozambique-cabo-delgado': {   'country': '모잠비크 (Mozambique)',
                                   'countryEn': 'Mozambique',
                                   'humidity': {'avg': 75, 'desc': '연안 평균 75% / 최고 95%', 'max': 95},
                                   'specialHazards': ['맹그로브 갯벌 중장비 기동 불가', '초고염분 해무 센서 산화/부식', '몬순 열대성 폭우'],
                                   'tempRange': {'desc': '열대 해안 (20°C ~ 36°C)', 'max': 36, 'min': 20},
                                   'terrainDescription': '인도양 해안을 따라 빽빽한 맹그로브 갯벌과 열대 수림. 조수간만의 차가 크고 연안 초고염분 해무가 극심함.',
                                   'terrainPhoto': {   'caption': '모잠비크 카보델가도 연안 맹그로브 해안 실사',
                                                       'location': '카보델가도주 가스전 연안',
                                                       'tags': ['맹그로브', '초고염분 해무', '열대 밀림'],
                                                       'url': 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Fishing_with_a_communal_net_off_the_coast_of_Mozambique_Africa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                   'terrainType': '인도양 연안 맹그로브 & 해안 밀림'},
    'myanmar-civil-war': {   'country': '미얀마 (Myanmar)',
                             'countryEn': 'Myanmar',
                             'humidity': {'avg': 85, 'desc': '몬순 시즌 98% 초극고습', 'max': 98},
                             'specialHazards': [   '상대습도 98% 광학계 렌즈 결로 및 배선 부식',
                                                   '몬순 진흙탕으로 차륜 장갑차 기동 마비',
                                                   '밀림 캐노피 위성/드론 관측 차단'],
                             'tempRange': {'desc': '열대 몬순 (18°C ~ 40°C)', 'max': 40, 'min': 18},
                             'terrainDescription': '샨주·카친주의 험준한 산악을 뒤덮은 빽빽한 열대우림. 몬순 시즌 연중 폭우로 지표면이 늪지로 변하고 시계가 20m '
                                                   '이내로 제한.',
                             'terrainPhoto': {   'caption': '미얀마 샨주 열대 몬순 산악 정글 밀림 실사',
                                                 'location': '미얀마 북부 샨주 정글 산악',
                                                 'tags': ['열대 몬순 정글', '98% 초극고습', '광학 결로 위험'],
                                                 'url': 'https://upload.wikimedia.org/wikipedia/commons/2/20/Indein%2C_Shan_Plateau%2C_Buddhist_monk%2C_Shan_State%2C_Shan_Hills%2C_Myanmar.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                             'terrainType': '열대 몬순 정글 & 산악 밀림 지대'},
    'nigeria-boko-haram': {   'country': '나이지리아 북동부 (Nigeria)',
                              'countryEn': 'Nigeria',
                              'humidity': {'avg': 35, 'desc': '건기 35% / 우기 85%', 'max': 85},
                              'specialHazards': ['갈대 늪지 수륙양용 장갑차 침하', '사헬 건기 미세 모래바람', '고온 열기 배터리 수명 저하'],
                              'tempRange': {'desc': '건조기 (18°C) ~ 최고 (44°C)', 'max': 44, 'min': 18},
                              'terrainDescription': '차드호 주변의 수천 개 갈대 군락 섬과 모래 평원. 게릴라 세력이 보트로 기습 후 은닉하기에 최적화된 수륙 혼재 '
                                                    '지형.',
                              'terrainPhoto': {   'caption': '나이지리아 북동부 차드호 분지 갈대 습지 실사',
                                                  'location': '보르노주 차드호 수역',
                                                  'tags': ['차드호 습지', '사헬 모래', '수륙 혼재'],
                                                  'url': 'https://upload.wikimedia.org/wikipedia/commons/1/16/Africa_%281878%29_%2814589687600%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                              'terrainType': '차드호 갈대 분지 늪지 & 건조 사헬'},
    'pakistan-conflict': {   'country': '파키스탄 북서부 / 발루치스탄 (Pakistan)',
                             'countryEn': 'Pakistan',
                             'humidity': {'avg': 30, 'desc': '건조 (30%)', 'max': 60},
                             'specialHazards': ['건조 황토 분진 기계류 침투', '산악 통로 고립 매복', '하계 건천 돌발 홍수'],
                             'tempRange': {'desc': '동절기 (-3°C) ~ 하계 (45°C)', 'max': 45, 'min': -3},
                             'terrainDescription': '메마른 암석 산과 깊은 건천(Wadi). 산악 도로가 취약하고 게릴라 세력이 동굴 진지를 구축하기에 유리함.',
                             'terrainPhoto': {   'caption': '파키스탄 발루치스탄 건조 암석 산악 및 협곡 실사',
                                                 'location': '카이베르 통로 및 발루치 산악',
                                                 'tags': ['건조 암석 산악', '황토 분진', '협곡 매복'],
                                                 'url': 'https://upload.wikimedia.org/wikipedia/commons/5/57/Balochistan_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                             'terrainType': '건조 암석 산악 협곡 & 황토 고원'},
    'russia-ukraine-war': {   'country': '우크라이나 (Ukraine)',
                              'countryEn': 'Ukraine',
                              'humidity': {'avg': 68, 'desc': '평균 68% / 해빙기 88% 고습', 'max': 88},
                              'specialHazards': [   '해빙기 라스푸티차(심층 연약지반 궤도 침하)',
                                                    '동절기 영하 20도 이하 결빙 및 설원 기동',
                                                    '개활 평원 드론 관측 노출'],
                              'tempRange': {'desc': '동절기 혹한 (-22°C) ~ 하계 온난 (34°C)', 'max': 34, 'min': -22},
                              'terrainDescription': '드니프로강 동부 끝없이 펼쳐진 흑토 스텝 평원. 수목 은폐물이 적고 시계가 광활하나, 봄·가을 해빙기 '
                                                    '라스푸티차(Rasputitsa)로 지표면이 1m 깊이의 진흙탕으로 변모.',
                              'terrainPhoto': {   'caption': '우크라이나 드니프로 동부 흑토 스텝 평원 실사',
                                                  'location': '동부 도네츠크·자포리자 전선',
                                                  'tags': ['흑토 스텝', '개활 평원', '라스푸티차 취약'],
                                                  'url': 'https://upload.wikimedia.org/wikipedia/commons/9/92/Granite-steppe_lands_of_Buh-3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                              'terrainType': '개활 스텝 평원 & 흑토(Chernozem) 지대'},
    'sahel-insurgency': {   'country': '말리 / 니제르 / 부르키나파소 (Sahel)',
                            'countryEn': 'Sahel',
                            'humidity': {'avg': 15, 'desc': '극건조 (평균 15%)', 'max': 40},
                            'specialHazards': ['주간 49°C 살인적 지표열', '초미세 사막 모래 엔진 흡입 마모', '광활한 사막 장거리 유류 보급'],
                            'tempRange': {'desc': '동절기 야간 (14°C) ~ 주간 혹서기 (49°C)', 'max': 49, 'min': 14},
                            'terrainDescription': '수백 km에 걸쳐 펼쳐진 사하라 모래언덕과 바위 지대. 엄폐물이 전무하고 지표면 온도가 60도에 육박하는 극한 사막 '
                                                  '전장.',
                            'terrainPhoto': {   'caption': '사헬 사하라 남단 황색 모래언덕 및 황무지 실사',
                                                'location': '말리-니제르-부르키나파소 3국 접경지',
                                                'tags': ['사하라 사막', '극초고온 49도', '초미세 모래'],
                                                'url': 'https://upload.wikimedia.org/wikipedia/commons/6/6b/LSRA_Dunes_Landscape_%2849991871846%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                            'terrainType': '사하라 남단 황색 모래언덕 & 암석 사막'},
    'somalia-al-shabaab': {   'country': '소말리아 (Somalia)',
                              'countryEn': 'Somalia',
                              'humidity': {'avg': 55, 'desc': '연안 85% / 내륙 55%', 'max': 85},
                              'specialHazards': ['인도양 고염분 해풍 부식', '가시덤불로 인한 보병 수색 장애', '미세 모래 광학계 스크래치'],
                              'tempRange': {'desc': '연중 고온 (22°C ~ 43°C)', 'max': 43, 'min': 22},
                              'terrainDescription': '모가디슈를 낀 인도양 해안 사구와 내륙의 메마른 아카시아 가시덤불 관목림. 강한 해풍과 모래 분진이 상시 발생.',
                              'terrainPhoto': {   'caption': '소말리아 인도양 연안 건조 사구 및 관목림 실사',
                                                  'location': '남부 인도양 연안 회랑',
                                                  'tags': ['연안 사구', '가시덤불', '해풍 염분'],
                                                  'url': 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Tianyu-8.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                              'terrainType': '인도양 연안 사구 & 건조 가시덤불 사바나'},
    'south-china-sea-disputes': {   'country': '남중국해 (South China Sea)',
                                    'countryEn': 'South China Sea',
                                    'humidity': {'avg': 80, 'desc': '열대 해양 80~95%', 'max': 95},
                                    'specialHazards': [   '염분 비말(Salt Spray)로 인한 센서 부식',
                                                          '카테고리 4~5급 슈퍼태풍 파고',
                                                          '천해 산호초 함정 좌초 위험'],
                                    'tempRange': {'desc': '열대 해양 (23°C ~ 37°C)', 'max': 37, 'min': 23},
                                    'terrainDescription': '스프래틀리/파라셀 군도의 인공섬 요새와 산호초. 열대 해양의 고온다습과 연례 슈퍼태풍이 통과하는 가혹한 '
                                                          '해양 환경.',
                                    'terrainPhoto': {   'caption': '남중국해 산호초 군도 및 열대 원해 해역 실사',
                                                        'location': '스프래틀리 군도 및 스카버러 암초',
                                                        'tags': ['산호초 군도', '슈퍼태풍', '극초염분 해무'],
                                                        'url': 'https://upload.wikimedia.org/wikipedia/commons/7/78/North_and_South_Luconia_Shoals.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                    'terrainType': '산호초 군도, 천해 석호 & 열대 원해 해역'},
    'south-sudan-conflict': {   'country': '남수단 (South Sudan)',
                                'countryEn': 'South Sudan',
                                'humidity': {'avg': 65, 'desc': '우기 최고 92% 극고습', 'max': 92},
                                'specialHazards': ['우기 광범위한 침수 및 연약 늪지', '초고습 환경 전자장비 곰팡이/부식', '말라리아 및 방역 취약'],
                                'tempRange': {'desc': '열대 온난 (20°C) ~ 최고 (41°C)', 'max': 41, 'min': 20},
                                'terrainDescription': '백나일강 유역의 세계 최대급 담수 습지대. 우기(5~10월) 동안 평원 전체가 침수되어 중장비의 지상 기동이 '
                                                      '불가능함.',
                                'terrainPhoto': {   'caption': '남수단 백나일 유역 수드(Sudd) 거대 습지 실사',
                                                    'location': '유니티주 백나일 대습지',
                                                    'tags': ['거대 늪지', '우기 침수', '고온다습'],
                                                    'url': 'https://upload.wikimedia.org/wikipedia/commons/5/59/MAJESTIC_VIEW_OF_WHITE_NILE_%2C_JUBA%2C_SOUTH_SUDAN.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                'terrainType': '수드(Sudd) 거대 습지 & 열대 사바나'},
    'sudan-civil-war': {   'country': '수단 (Sudan)',
                           'countryEn': 'Sudan',
                           'humidity': {'avg': 25, 'desc': '건조 (평균 25%)', 'max': 60},
                           'specialHazards': ['수천 미터 높이의 하부브 모래벽', '주간 47도 극한 지표열', '냉각수 증발 및 엔진 과열'],
                           'tempRange': {'desc': '온난 (15°C) ~ 혹서기 (47°C)', 'max': 47, 'min': 15},
                           'terrainDescription': '나일강 주변을 제외하면 건조한 관목과 붉은 모래 평원. 거대한 적란운과 함께 불어닥치는 하부브(Haboob) 모래폭풍 '
                                                 '발원지.',
                           'terrainPhoto': {   'caption': '수단 사헬 지대 붉은 점토토 평원 및 건조 사바나 실사',
                                               'location': '하르툼 외곽 & 다르푸르 평원',
                                               'tags': ['사헬 평원', '하부브 모래폭풍', '적색 점토토'],
                                               'url': 'https://upload.wikimedia.org/wikipedia/commons/c/cc/COSV_-_Darfur_2006_-_Contesto.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                           'terrainType': '사헬 반건조 사바나 & 붉은 점토토'},
    'syria-civil-war': {   'country': '시리아 (Syria)',
                           'countryEn': 'Syria',
                           'humidity': {'avg': 35, 'desc': '건조 (평균 35%)', 'max': 60},
                           'specialHazards': ['점토질 미세 흙먼지 흡입 마모', '폭염 시 냉각 효율 저하', '도심 잔해 지뢰/IED 매설'],
                           'tempRange': {'desc': '동절기 (2°C) ~ 사막 폭염 (43°C)', 'max': 43, 'min': 2},
                           'terrainDescription': '바디야 반사막 평원과 농경 구릉, 폐허가 된 콘크리트 시가지. 건조한 점토질 미세 흙먼지가 전차 공기 흡기 계통을 위협함.',
                           'terrainPhoto': {   'caption': '시리아 바디야 반사막 평원 및 건조 구릉 실사',
                                               'location': '이들립-알레포 외곽 반사막 평원',
                                               'tags': ['반사막 평원', '점토질 흙먼지', '파괴 도시'],
                                               'url': 'https://upload.wikimedia.org/wikipedia/commons/d/db/Syrian_desert_near_Palmyra%2C_Dusk%2C_Syria.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                           'terrainType': '내륙 반건조 사막 평원 & 파괴된 도심지'},
    'taiwan-strait-tensions': {   'country': '대만 해협 & 대만 (Taiwan Strait)',
                                  'countryEn': 'Taiwan',
                                  'humidity': {'avg': 75, 'desc': '해양 다습 (75~95%)', 'max': 95},
                                  'specialHazards': [   '초고염분 해무에 의한 레이더 안테나 부식',
                                                        '해협 강풍 및 높은 파고(Sea State 5+)',
                                                        '서해안 연약 갯벌 상륙 방해'],
                                  'tempRange': {'desc': '아열대 (13°C ~ 36°C)', 'max': 36, 'min': 13},
                                  'terrainDescription': '해협의 거센 조류와 계절풍, 대만 서해안의 넓은 개펄, 동부의 험준한 중앙산맥. 태풍과 초고염분 해무가 상시 '
                                                        '노출.',
                                  'terrainPhoto': {   'caption': '대만 해협 연안 해상 및 펑후제도 전경 실사',
                                                      'location': '대만 해협 중간선 및 펑후제도',
                                                      'tags': ['대만 해협', '초고염분 해무', '중앙산맥'],
                                                      'url': 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Aerial_photograph_of_the_main_island_in_Penghu_on_12_July_2011.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                  'terrainType': '평균 수심 60m 해협, 연안 갯벌 & 3,000m 중앙산맥'},
    'turkey-kurdish-conflict': {   'country': '튀르키예 동부 / 쿠르드 (Turkiye / Kurdistan)',
                                   'countryEn': 'Turkiye',
                                   'humidity': {'avg': 45, 'desc': '평균 45%', 'max': 70},
                                   'specialHazards': ['겨울철 폭설로 도로 폐쇄 및 결빙', '급경사 산악 장갑차 등판 불가', '고산지 희박 공기 엔진 출력 저하'],
                                   'tempRange': {'desc': '고산 혹한 (-18°C) ~ 하계 온난 (35°C)', 'max': 35, 'min': -18},
                                   'terrainDescription': '해발 2,000~3,500m에 이르는 가파른 바위산과 좁은 계곡. 겨울철 폭설과 맹렬한 혹한이 지상 기동을 '
                                                         '전면 차단함.',
                                   'terrainPhoto': {   'caption': '동부 아나톨리아 고산 암벽 및 험준 협곡 실사',
                                                       'location': '튀르키예-이라크 국경 산악 지대',
                                                       'tags': ['고산 협곡', '적설 결빙', '험준 암반'],
                                                       'url': 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Khor_Virap_Monastery_and_Mount_Ararat%2C_Armenia.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                                   'terrainType': '동부 아나톨리아 고산 암벽 & 깊은 계곡'},
    'yemen-war': {   'country': '예멘 & 홍해 (Yemen / Red Sea)',
                     'countryEn': 'Yemen',
                     'humidity': {'avg': 40, 'desc': '내륙 40% 건조 / 홍해 연안 85% 고염무', 'max': 85},
                     'specialHazards': ['홍해 연안 초고염분 금속 부식', '하부브(Haboob) 모래폭풍', '화산암 쇄석 타이어/궤도 마모'],
                     'tempRange': {'desc': '야간 (12°C) ~ 주간 혹서기 (48°C)', 'max': 48, 'min': 12},
                     'terrainDescription': '험준한 화산암 암벽과 해안 사구. 홍해 연안의 극심한 고온다습 염분 환경과 내륙의 건조 바위산이 복합된 극한 환경.',
                     'terrainPhoto': {   'caption': '예멘 하라즈 화산암 고산 지대 및 건조 협곡 실사',
                                         'location': '서부 사나-호데이다 산악 회랑',
                                         'tags': ['화산암 사막', '초고염분 해협', '극고온'],
                                         'url': 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Khalil_Village%2C_Yemen_%2823185876182%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original'},
                     'terrainType': '화산암 산악, 해안 건조 사막 & 바브엘만데브 해협'}}

# 한화 방산 18대 핵심 무기체계 포트폴리오 (한화에어로스페이스 · 한화시스템 · 한화오션)
# MIL-STD-810H 전장 운용 스펙, 온도/습도 허용치 및 지형 적합도 포함
HANWHA_DEFENSE_PORTFOLIO = [   {   'id': 'K9_THUNDER',
        'nameKo': 'K9 자주포 & K10 탄약운반장갑차',
        'company': '한화에어로스페이스',
        'category': '화력/기동',
        'caliber': '155mm / 52구경장',
        'description': '글로벌 점유율 50% 이상의 대표 K-방산 자주포. NATO 표준 호환, 분당 6~8발 급속사격, 자동화 사격통제.',
        'threatScenarios': ['포격전', '장거리 화력지원', '진지 파괴', '대포병 사격', '전면 지상전'],
        'targetRegions': ['동유럽', '북유럽', '중동', '서남아시아', '동남아시아'],
        'keywords': ['자주포', '155mm', '포격', '화력', 'k9', 'k-9', '포탄', '대포병', '사거리', '탄약운반차'],
        'operatingSpecs': {   'tempRange': '-40°C ~ +50°C (MIL-STD-810H)',
                              'tempMin': -40,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': 'MIL-STD-810H / NATO STANAG',
                              'protection': '양압 화생방(NBC) / 155mm 포탄 파편 및 14.5mm 철갑탄 방호',
                              'terrainFit': {'평원': 95, '사막': 90, '산악': 75, '정글': 60, '해양': 20, '도심지': 70},
                              'primaryEnvironments': ['혹한/설원', '개활 스텝 평원', '사막/구릉'],
                              'fieldConstraints': '해빙기 라스푸티차 진흙탕 기동 시 광폭 궤도 패드(Wide Track Pads) 장착 필수; 정글 고습도 환경 시 광학 '
                                                  '렌즈 결로 방지 열선 가동 및 방청 그리스 도포 주기 단축 필요',
                              'countermeasurePackage': '혹한기 보조동력장치(APU) 예열 킷 / 라스푸티차 광폭 궤도 / 사막형 샌드 프리클리너'}},
    {   'id': 'CHEONMU_MLRS',
        'nameKo': '천무 다련장로켓 (K-MLRS / Chunmoo)',
        'company': '한화에어로스페이스',
        'category': '정밀유도/화력',
        'range': '80km ~ 290km 유도미사일',
        'description': '130mm 무유도로켓부터 239mm 유도로켓, 290mm 전술지대지유도탄(CTM-290)까지 운용 가능한 다연장 화력체계.',
        'threatScenarios': ['원거리 정밀 타격', '종심 타격', '적 지휘부/방공망 무력화', '해안 방어'],
        'targetRegions': ['동유럽', '중동', '동아시아', '동남아시아'],
        'keywords': ['다련장', '천무', '로켓', '유도탄', 'mlrs', 'himars', '정밀타격', 'ctm-290', '원거리'],
        'operatingSpecs': {   'tempRange': '-35°C ~ +50°C (MIL-STD-810H)',
                              'tempMin': -35,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': 'MIL-STD-810H / 차륜형 8x8 고기동 차체',
                              'protection': '소총탄 및 포탄 파편 방호 / 캐빈 양압 NBC',
                              'terrainFit': {'평원': 95, '사막': 92, '산악': 65, '정글': 55, '해양': 40, '도심지': 75},
                              'primaryEnvironments': ['개활 평원', '사막 도로망', '해안 방어 진지'],
                              'fieldConstraints': '차체 회전반경(13m)으로 비포장 정글 급경사로 진입 제한; 사막 작전 시 유도탄 캐니스터 밀폐 실링 점검 및 발사대 '
                                                  '먼지 유입 차단 필수',
                              'countermeasurePackage': '사막형 타이어 공기압 자동조절(CTIS) / 밀폐형 유도탄 포드 캐니스터 씰'}},
    {   'id': 'REDBACK_IFV',
        'nameKo': '레드백(Redback) 미래형 궤도장갑차 / K21',
        'company': '한화에어로스페이스',
        'category': '기동/방호',
        'description': '호주 육군 LAND 400 선정 차세대 보병전투장갑차(IFV). 능동방호체계(APS), 30mm 기관포, 대전차미사일 탑재.',
        'threatScenarios': ['도시 기동전', '대전차 미사일 방호', '기계화보병 수송', '복합 지상전'],
        'targetRegions': ['오세아니아', '동유럽', '서유럽', '중동'],
        'keywords': ['장갑차', '레드백', '보병전투', 'ifv', '방호', '기동', 'k21', 'aps', '기관포'],
        'operatingSpecs': {   'tempRange': '-40°C ~ +50°C (MIL-STD-810H)',
                              'tempMin': -40,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': 'STANAG 4569 레벨 4/6 방호',
                              'protection': '복합고무궤도(CRT) / 아이언피스트 능동방호(APS) / 완벽 밀폐 NBC',
                              'terrainFit': {'평원': 95, '사막': 92, '산악': 80, '정글': 75, '해양': 30, '도심지': 95},
                              'primaryEnvironments': ['도시 시가전', '스텝 평원', '연약지반', '사막'],
                              'fieldConstraints': '복합고무궤도로 라스푸티차/모래 기동력 탁월하나, 정글 밀림 유입물(덩굴/수목)에 의한 능동방호 레이더 센서 오염 주의',
                              'countermeasurePackage': '열대 정글용 센서 방호 가드 / 복합고무궤도 진흙 자동 배출 휠'}},
    {   'id': 'CHEONGUNG_II',
        'nameKo': '천궁-II (M-SAM) 중거리 지대공 유도무기',
        'company': '한화시스템 / 한화에어로스페이스',
        'category': '방공/대공미사일',
        'description': '탄도탄 및 항공기 요격용 한국형 패트리어트. MFR 다기능 레이더와 히트투킬(Hit-to-Kill) 정밀 요격 미사일.',
        'threatScenarios': ['탄도미사일 위협', '순항미사일 요격', '적기 침투', '복합 공중위협'],
        'targetRegions': ['중동', '동유럽', '동아시아'],
        'keywords': ['천궁', 'm-sam', '방공', '요격', '지대공', '패트리어트', '탄도탄', '미사일 방어', 'mfr', '레이더'],
        'operatingSpecs': {   'tempRange': '-40°C ~ +50°C (전천후)',
                              'tempMin': -40,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': 'MIL-STD-810H 전천후 요격 체계',
                              'protection': 'MFR 다기능 레이더 밀폐 수냉 / 수직발사관 방수 실링',
                              'terrainFit': {'평원': 95, '사막': 95, '산악': 70, '정글': 65, '해양': 80, '도심지': 85},
                              'primaryEnvironments': ['사막 평원', '해안 거점', '스텝 평원'],
                              'fieldConstraints': '사막 미세 모래폭풍 시 MFR 위상배열 레이더 냉각핀 및 송수신 모듈 필터 일일 세척 필수; 고습도 염무 환경 시 레이돔 '
                                                  '부식 방지 코팅 유지',
                              'countermeasurePackage': '사막형 고출력 레이더 칠러(Chiller) / 해안 내염형 레이돔 코팅'}},
    {   'id': 'L_SAM',
        'nameKo': 'L-SAM 장거리 지대공 유도무기 & 초고고도 방어',
        'company': '한화에어로스페이스 / 한화시스템',
        'category': '방공/탄도탄방어',
        'description': '고도 40~60km 상공에서 적 탄도미사일을 요격하는 한국형 사드(THAAD)급 상층 방어체계.',
        'threatScenarios': ['중장거리 탄도탄', '극초음속 무기', '상층 공중위협'],
        'targetRegions': ['동아시아', '중동'],
        'keywords': ['l-sam', '엘샘', '장거리 지대공', '사드', 'thaad', '상층방어', '고고도 요격'],
        'operatingSpecs': {   'tempRange': '-40°C ~ +50°C',
                              'tempMin': -40,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': 'MIL-STD-810H 고고도 탄도탄 방어',
                              'protection': '대형 전술차량 / 고출력 GaN S-밴드 AESA 레이더',
                              'terrainFit': {'평원': 95, '사막': 95, '산악': 60, '정글': 50, '해양': 75, '도심지': 80},
                              'primaryEnvironments': ['내륙 개활지', '사막 거점', '후방 전략기지'],
                              'fieldConstraints': '대형 차량 특성상 협소 정글로 기동 불가, 사막 평원 및 후방 비행장/전략 거점 고정 방열 최적',
                              'countermeasurePackage': '방진·방사막 특수 쉘터 / 전략 거점 전원 안정화 제너레이터'}},
    {   'id': 'LASER_AIR_DEFENSE',
        'nameKo': '레이저 대공무기 (Block-I) / 안티드론 솔루션',
        'company': '한화에어로스페이스 / 한화시스템',
        'category': '미래/드론대응',
        'description': '광섬유 레이저 빔으로 적 소형 드론 및 무인기를 1회 발사비용 약 2천원으로 격추하는 미래 전장의 게임체인저.',
        'threatScenarios': ['소형 드론 공격', '자폭 무인기 군집 침투', '정찰 드론', '비대칭 공중 침투'],
        'targetRegions': ['중동', '동유럽', '동아시아', '남아시아'],
        'keywords': ['레이저', '드론', '무인기', '안티드론', '카운터드론', '요격', '샤헤드', '자폭드론', 'uav'],
        'operatingSpecs': {   'tempRange': '-25°C ~ +45°C',
                              'tempMin': -25,
                              'tempMax': 45,
                              'maxHumidity': 90,
                              'standard': '밀폐형 방진/방수 레이저 옵틱스',
                              'protection': '광섬유 레이저 발진기 / 열교환 칠러',
                              'terrainFit': {'평원': 90, '사막': 85, '산악': 70, '정글': 60, '해양': 80, '도심지': 95},
                              'primaryEnvironments': ['공군기지', '국경 철책선', '도시 핵심시설', '원자력/유류 저장소'],
                              'fieldConstraints': '짙은 안개, 몬순 폭우, 극심한 모래폭풍 시 레이저 빔 산란으로 유효사거리 30~50% 감소; 고습도 환경 광학 '
                                                  '창(Optical Window) 결로 방지 가열 필수',
                              'countermeasurePackage': '광학창 에어커튼 및 김서림 방지 열선 / 고효율 레이저 칠러'}},
    {   'id': 'BIHO_HYBRID',
        'nameKo': '비호복합 대공포 & 단거리 복합방공',
        'company': '한화에어로스페이스',
        'category': '방공/근접방어',
        'description': '30mm 쌍열 자주대공포와 신궁 지대공유도탄을 결합하여 저고도로 침투하는 적기 및 무인기를 격멸.',
        'threatScenarios': ['저고도 침투', '헬기 공격', '순항미사일 근접 방어', '드론 방어'],
        'targetRegions': ['중동', '동남아시아', '동유럽'],
        'keywords': ['비호', '대공포', '복합', '저고도', '30mm', '신궁', '근접방공'],
        'operatingSpecs': {   'tempRange': '-35°C ~ +50°C (MIL-STD-810G)',
                              'tempMin': -35,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': 'MIL-STD-810G 복합방공 체계',
                              'protection': '궤도형 차체 / TPS-830K 레이더 / EOTS 광학추적',
                              'terrainFit': {'평원': 90, '사막': 90, '산악': 85, '정글': 70, '해양': 40, '도심지': 90},
                              'primaryEnvironments': ['기계화부대 진격로', '산악 협곡', '도시 외곽 방공'],
                              'fieldConstraints': '연약지반 기동력 우수하나, 정글 다습 환경에서 신궁 미사일 탐색기 냉각 가스 및 배터리 보관 수명 단축 주의',
                              'countermeasurePackage': 'EOTS 렌즈 방습 퍼징 키트 / 방수·방진 미사일 포드'}},
    {   'id': 'CHEONHO_AAGW',
        'nameKo': '30mm 차륜형대공포 천호(AAGW)',
        'company': '한화에어로스페이스 / 한화시스템',
        'category': '방공/근접방어',
        'caliber': '30mm 쌍열 (분당 1,200발)',
        'description': '기존 발칸포를 대체하여 K808 차륜형 차체에 고성능 전자광학추적장치(EOTS)와 30mm 쌍열포를 결합한 고기동 근접방공체계.',
        'threatScenarios': ['저고도 적기 침투', '자폭 드론 격추', '아군 기동대열 방호', '순항미사일 대응'],
        'targetRegions': ['중동', '동남아시아', '동유럽'],
        'keywords': ['천호', '대공포', 'aagw', '30mm', '차륜형대공포', 'eots', '저고도방공', '안티드론'],
        'operatingSpecs': {   'tempRange': '-32°C ~ +50°C',
                              'tempMin': -32,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': '차륜형 8x8 고기동 차체',
                              'protection': '런플랫 타이어 / EOTS 자동추적 / 차체 소총탄 방호',
                              'terrainFit': {'평원': 95, '사막': 92, '산악': 75, '정글': 65, '해양': 40, '도심지': 95},
                              'primaryEnvironments': ['도로망 신속 전개', '사막 평원', '도심지 방공'],
                              'fieldConstraints': '차륜형으로 도로망 및 사막 고속 기동에 최적화되었으나, 심층 라스푸티차 늪지대 진입 시 런플랫 타이어 견인력 저하 주의',
                              'countermeasurePackage': 'CTIS 타이어 공기압 조절기 / EOTS 김서림 방지 블로워'}},
    {   'id': 'KSS_III_SUBMARINE',
        'nameKo': '장보고-III (KSS-III Batch-II) 3,600톤급 잠수함',
        'company': '한화오션',
        'category': '해양/잠수함',
        'specs': '3,600톤급 / AIP + 리튬전지 / SLBM VLS',
        'description': '세계 최고 수준의 잠항지속능력을 갖춘 디젤 잠수함. 공기불요추진(AIP)과 리튬전지, SLBM 수직발사관을 탑재한 글로벌 전략 타격 플랫폼.',
        'threatScenarios': ['해양 영유권 분쟁', '해상 봉쇄 돌파', '전략 억제/SLBM 타격', '수중 정찰/대잠전'],
        'targetRegions': ['동아시아', '동남아시아', '유럽', '북미'],
        'keywords': ['잠수함', '장보고', 'kss-iii', 'batch-ii', '오르카', 'aip', '리튬전지', 'slbm', '수중', '해양'],
        'operatingSpecs': {   'tempRange': '-2°C ~ +35°C (해수 온도 기준)',
                              'tempMin': -2,
                              'tempMax': 35,
                              'maxHumidity': 100,
                              'standard': '심해 잠항 / 수중 음향 스텔스 규격',
                              'protection': 'HY-100 고장력강 선체 / 무반사 음향타일 / 리튬전지 3중 안전 시스템',
                              'terrainFit': {'해양': 100, '연안': 85, '군도/해협': 90, '평원': 0, '사막': 0, '정글': 0},
                              'primaryEnvironments': ['원해 전략 초계', '동해/남중국해 심해', '대만 해협 수중 매복'],
                              'fieldConstraints': '남중국해 천해(수심 50m 이하) 암초 지대 잠항 시 능동소나 및 해저 지형 충돌 주의; 열대 고수온 해역 리튬 배터리 '
                                                  '팩 냉각 모니터링 필수',
                              'countermeasurePackage': '열대 해역 고효율 해수 냉각 시스템 / 연안 천해 정밀 장애물 회피 소나'}},
    {   'id': 'FFX_KDDX_FRIGATE',
        'nameKo': 'FFX Batch-III(울산급) / KDDX 차기구축함',
        'company': '한화오션 / 한화시스템',
        'category': '해양/수상함',
        'specs': '복합센서마스트(I-MAST) / 4면 AESA 레이더',
        'description': '한화오션의 첨단 함정 설계와 한화시스템의 복합센서마스트(I-MAST) 및 통합전투체계(CMS)가 결합된 대한민국 해군 핵심 수상 전투함.',
        'threatScenarios': ['대함 미사일 방어', '해상 교통로 보호', '연안/원해 초계', '잠수함 탐지'],
        'targetRegions': ['동남아시아', '동아시아', '남미', '중동'],
        'keywords': ['호위함', '구축함', '울산급', 'ffx', 'kddx', '함정', '해군', '수상함', 'i-mast', '전투함'],
        'operatingSpecs': {   'tempRange': '-25°C ~ +45°C (해상 대기)',
                              'tempMin': -25,
                              'tempMax': 45,
                              'maxHumidity': 100,
                              'standard': 'Sea State 6-7 내항성 / 초고염분 해무 내성',
                              'protection': '스텔스 선체 / I-MAST 밀폐 복합센서마스트',
                              'terrainFit': {'해양': 100, '연안': 95, '군도/해협': 90, '평원': 0, '사막': 0, '정글': 0},
                              'primaryEnvironments': ['홍해/말라카 해협 호송', '남중국해 초계', '원양 작전'],
                              'fieldConstraints': '홍해/남중국해 초고염분 환경 장기 항해 시 I-MAST 4면 AESA 레이더 담수 세척 주기 엄수 및 해양 따개비 부착 '
                                                  '방지 선저 관리',
                              'countermeasurePackage': '통합 담수 세척 스프링클러 / 선체 음극 방식(ICCP) 및 고내구성 방오 도료'}},
    {   'id': 'GHOST_COMMANDER_MUMT',
        'nameKo': '무인전력지휘통제함(Ghost Commander) & 전투용 XLUUV',
        'company': '한화오션',
        'category': '해양/무인전투',
        'specs': '해양 유무인 복합전투(MUM-T) 기함',
        'description': '무인수상정(USV), 무인잠수정(UUV), 무인항공기(UAV)를 모함에서 자율 전개·지휘하는 미래 스마트 네이비 유무인 복합전투 사령탑.',
        'threatScenarios': ['무인 정찰/감시', '기뢰 탐색/소해', '위험해역 선견작전', '해상 군집 공격 대응'],
        'targetRegions': ['북미', '동아시아', '중동'],
        'keywords': ['고스트커맨더', '무인함', 'xluuv', 'uuv', 'usv', '유무인복합', 'mum-t', '해양드론'],
        'operatingSpecs': {   'tempRange': '-20°C ~ +45°C',
                              'tempMin': -20,
                              'tempMax': 45,
                              'maxHumidity': 100,
                              'standard': 'MUM-T 해양 유무인 복합 지휘 체계',
                              'protection': '스텔스 모함 설계 / 자율 무인정 진수·회수(LARS)',
                              'terrainFit': {'해양': 98, '연안': 95, '군도/해협': 95, '평원': 0, '사막': 0, '정글': 0},
                              'primaryEnvironments': ['기뢰 위험 해역', '분쟁 군도 정찰', '원격 봉쇄 작전'],
                              'fieldConstraints': '열대 태풍(Sea State 5 이상) 발생 시 소형 USV/UUV 발진 및 회수 안전 제한; 위성 데이터링크 통신 두절 '
                                                  '시 자율 귀환 모드 작동',
                              'countermeasurePackage': '파도 보상형 전동 LARS 크레인 / 다중 위성 백업 통신 시스템'}},
    {   'id': 'NAVAL_SYSTEMS',
        'nameKo': '함정용 통합전투체계 & 해양 복합센서',
        'company': '한화시스템',
        'category': '해양/센서',
        'description': 'KDDX 차기구축함 및 호위함 통합 전투체계(CMS), 다기능 위상배열레이더(MFR) 및 정밀 소나체계.',
        'threatScenarios': ['해상 봉쇄', '잠수함 위협', '해양 영유권 분쟁', '대함 미사일 방어', '연안 방어'],
        'targetRegions': ['동아시아', '동남아시아', '중동', '남미'],
        'keywords': ['함정', '구축함', '호위함', '해군', '해상', '전투체계', 'aesa', '소나', '리튬전지', '해양'],
        'operatingSpecs': {   'tempRange': '-25°C ~ +50°C',
                              'tempMin': -25,
                              'tempMax': 50,
                              'maxHumidity': 100,
                              'standard': '해군 규격 함정 통합전투체계 (MIL-S-901D 내충격)',
                              'protection': '내충격(MIL-S-901D) / 방진·내염밀폐 전자 캐비닛',
                              'terrainFit': {'해양': 100, '연안': 95, '군도/해협': 90, '평원': 0, '사막': 0, '정글': 0},
                              'primaryEnvironments': ['수상함/잠수함 CMS 통제실'],
                              'fieldConstraints': '열대 해역 고온다습 시 전산 콘솔 및 서버 캐비닛 공조 에어컨 중단 방지 관리',
                              'countermeasurePackage': '이중화 캐비닛 수냉 칠러 / 방염 코팅 회로기판'}},
    {   'id': 'KF21_AESA_RADAR',
        'nameKo': 'KF-21 한국형 전투기용 AESA 레이더 & 항전체계',
        'company': '한화시스템',
        'category': '항공/센서',
        'specs': '1,000+ GaN TR모듈 / 다중표적 동시추적',
        'description': '미국 기술이전 없이 독자 개발에 성공한 한국형 전투기(KF-21)의 핵심 두뇌. 공대공·공대지·공대함 다중 표적을 원거리에서 정밀 동시 탐색 및 추적.',
        'threatScenarios': ['원거리 공중전', '적 스텔스기 탐색', '정밀 공대지 타격 유도', '전자전 방해 극복'],
        'targetRegions': ['동유럽', '동아시아', '중동', '동남아시아'],
        'keywords': ['aesa', '레이더', 'kf-21', '보라매', '항전', '전투기', '공중전', '공대공', '표적추적'],
        'operatingSpecs': {   'tempRange': '-55°C ~ +70°C (초음속 고고도 비행)',
                              'tempMin': -55,
                              'tempMax': 70,
                              'maxHumidity': 95,
                              'standard': 'MIL-STD-810H 항공 규격',
                              'protection': 'GaN TR모듈 액체냉각 / 레이돔 전자기 투과',
                              'terrainFit': {'평원': 100, '사막': 100, '산악': 95, '정글': 95, '해양': 100, '도심지': 100},
                              'primaryEnvironments': ['전 고도 공역', '초음속 공대공/공대지'],
                              'fieldConstraints': '사막 기지 주기 시 레이돔 미세 모래 스크래치 방지 보호 커버 장착 필수',
                              'countermeasurePackage': '사막용 레이돔 보호 실드 / 지상 예열 및 액체냉각 카트'}},
    {   'id': 'AERO_TURBOFAN_ENGINE',
        'nameKo': '첨단 항공 가스터빈 엔진 (KF-21 F414 & 차세대 터보팬)',
        'company': '한화에어로스페이스',
        'category': '항공/추진',
        'specs': '21,500lbf급 후기연소기 추력 / FADEC',
        'description': '대한민국 유일의 가스터빈 항공엔진 제작사(누적 10,000대 생산 돌파). KF-21 탑재 F414 엔진 양산 및 15,000lbf급 차세대 독자 군용 터보팬 엔진 '
                       'R&D.',
        'threatScenarios': ['항공 추진체계 자립', '초음속 비행', '장거리 항공 초계', '전술 무인기 엔진'],
        'targetRegions': ['동유럽', '동남아시아', '북미'],
        'keywords': ['항공엔진', '가스터빈', '엔진', 'f414', '터보팬', 'kf-21', '추진체계', '제트엔진'],
        'operatingSpecs': {   'tempRange': '-55°C ~ +55°C',
                              'tempMin': -55,
                              'tempMax': 55,
                              'maxHumidity': 95,
                              'standard': 'MIL-E-5007D 군용 항공가스터빈 규격',
                              'protection': 'FADEC 이중화 디지털 제어',
                              'terrainFit': {'평원': 100, '사막': 95, '산악': 95, '정글': 95, '해양': 98, '도심지': 100},
                              'primaryEnvironments': ['초음속 비행 공역'],
                              'fieldConstraints': '사막/화산재 기역 이착륙 시 엔진 흡입구 이물질(FOD) 및 블레이드 침식 방지 주기적 내시경 검사',
                              'countermeasurePackage': '내마모성 세라믹 열차폐 코팅(TBC) / FOD 스크린'}},
    {   'id': 'TAIPERS_MISSILE',
        'nameKo': '천검(TAipers) 헬기/장갑차용 정밀유도 대전차미사일',
        'company': '한화에어로스페이스',
        'category': '정밀유도/기갑',
        'specs': '사거리 8km+ / 광섬유+무선 / AI 영상인식',
        'description': '이스라엘 스파이크(Spike)급 비가시선(NLOS) 장거리 정밀 타격 유도미사일. 유선 광섬유 및 무선 데이터링크, AI 딥러닝 기반 표적 자동인식(Fire & '
                       'Forget).',
        'threatScenarios': ['적 전차/기갑부대 파괴', '엄폐 진지 정밀타격', '헬기 공대지 공격', '도시 기동전'],
        'targetRegions': ['동유럽', '중동', '동남아시아'],
        'keywords': ['천검', '대전차', '대전차미사일', '유도탄', '스파이크', 'lah', '공대지', '장거리타격'],
        'operatingSpecs': {   'tempRange': '-32°C ~ +50°C',
                              'tempMin': -32,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': '비가시선(NLOS) 정밀 유도탄',
                              'protection': '밀폐형 발사 캐니스터 / 광섬유 스풀 방습',
                              'terrainFit': {'평원': 95, '사막': 95, '산악': 90, '정글': 70, '해양': 70, '도심지': 90},
                              'primaryEnvironments': ['기갑 매복', '산악 사격진지', '도시 대전차 방어'],
                              'fieldConstraints': '밀림 정글 발사 시 광섬유 유선 케이블이 나뭇가지/수목에 걸려 단선될 위험 존재 => 무선 데이터링크 모드로 자동 전환 '
                                                  '권장',
                              'countermeasurePackage': '무선 RF 데이터링크 전환 킷 / 캐니스터 방습 실링'}},
    {   'id': 'TIGON_WHEELED_IFV',
        'nameKo': '타이곤(TIGON) 6x6 차륜형 장갑차 & K105A1',
        'company': '한화에어로스페이스',
        'category': '기동/차륜형',
        'specs': '525마력 / 최고시속 100km / 수륙양용',
        'description': '궤도형이 부담스러운 국가를 위한 고기동·가성비 차륜형 장갑차. STANAG 레벨3 방호와 수륙양용 능력, 105mm 기동화력 지원 능력 완비.',
        'threatScenarios': ['신속 기동전', '사막/평원 수색', '국경 경비', '게릴라/비정규군 소탕'],
        'targetRegions': ['동남아시아', '아프리카', '중동', '중남미'],
        'keywords': ['타이곤', 'tigon', '차륜형', '장갑차', 'k105a1', '차륜형자주포', '기동', '수륙양용'],
        'operatingSpecs': {   'tempRange': '-32°C ~ +50°C',
                              'tempMin': -32,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': 'STANAG 4569 레벨 3 방호',
                              'protection': '런플랫 타이어 / 수륙양용 워터제트 / V자형 지뢰방호 선체',
                              'terrainFit': {'평원': 95, '사막': 95, '산악': 75, '정글': 70, '해양': 60, '도심지': 92},
                              'primaryEnvironments': ['도로망 신속 전개', '사막 순찰', '도심 치안 작전'],
                              'fieldConstraints': '수륙양용 도하 가능하나, 정글 몬순 급류(유속 2.5m/s 이상) 및 진흙 강변 접안 시 윈치 보조 필요',
                              'countermeasurePackage': 'CTIS 타이어 조절기 / 고출력 구난 윈치 & 차체 바닥 V-헐 방호'}},
    {   'id': 'SPACE_SAT_DEFENSE',
        'nameKo': '소형 SAR 정찰위성 & 저궤도 군위성통신망',
        'company': '한화시스템',
        'category': '우주/정찰/통신',
        'description': '주야간 악천후 관계없이 지상을 0.5m급 해상도로 감시하는 초소형 SAR 위성 및 미래 군용 저궤도 위성 통신.',
        'threatScenarios': ['지휘통제 단절', '통신 방해(EW)', '우주 기반 실시간 전장 감시', '장거리 표적 획득'],
        'targetRegions': ['동아시아', '동유럽', '중동'],
        'keywords': ['위성', 'sar', '우주', '정찰', '통신', 'c4i', '감시', '우주국방', '전자전'],
        'operatingSpecs': {   'tempRange': '-100°C ~ +120°C (우주 궤도 진공)',
                              'tempMin': -100,
                              'tempMax': 120,
                              'maxHumidity': 0,
                              'standard': '우주 환경 규격 (ECSS / NASA-STD)',
                              'protection': '초소형 0.5m급 고해상도 마이크로파 SAR 레이더',
                              'terrainFit': {'평원': 100, '사막': 100, '산악': 100, '정글': 100, '해양': 100, '도심지': 100},
                              'primaryEnvironments': ['500km 저궤도(LEO) 우주'],
                              'fieldConstraints': '지상의 악천후(구름, 폭우, 모래폭풍)를 100% 투과하여 정찰 가능하나, 정글 밀림 지하 시설은 지표 투과 '
                                                  '레이더(GPR) 추가 분석 필요',
                              'countermeasurePackage': 'L/X-밴드 복합 마이크로파 SAR 안테나 / 인공지능 표적 자동탐지 소프트웨어'}},
    {   'id': 'UGV_UNMANNED',
        'nameKo': '다목적 무인차량(Arion-SMET) & 자율로봇 체계',
        'company': '한화에어로스페이스',
        'category': '무인/자율체계',
        'description': '미 국방부 FCT(해외비교시험) 통과. 원격/자율주행 기반 물자수송, 부상자 후송, 원격사격통제(RCWS) 수색.',
        'threatScenarios': ['위험지역 수색', '군수물자 자율수송', '도시 시가전', '사상자 감축'],
        'targetRegions': ['북미', '유럽', '중동', '동아시아'],
        'keywords': ['무인차량', 'ugv', '아리온스멧', '로봇', '자율주행', 'rcws', '무인수색'],
        'operatingSpecs': {   'tempRange': '-30°C ~ +50°C',
                              'tempMin': -30,
                              'tempMax': 50,
                              'maxHumidity': 95,
                              'standard': '미 국방부 FCT 통과 / IP67 방수방진',
                              'protection': '원격사격통제(RCWS) / LiFePO4 배터리 팩 방진밀폐',
                              'terrainFit': {'평원': 95, '사막': 90, '산악': 80, '정글': 75, '해양': 30, '도심지': 95},
                              'primaryEnvironments': ['위험지역 수색', '군수품 자율수송', '시가전'],
                              'fieldConstraints': '밀림 정글에서 덩굴 및 울창한 하층 식생에 자율주행 라이다(LiDAR) 센서 차폐 발생 가능 => 딥러닝 영상 주행 보조 '
                                                  '모드 적용 필수',
                              'countermeasurePackage': 'LiDAR 렌즈 와이퍼 & 초음파 세척 노즐 / 전지형 올터레인 광폭 타이어'}}]
